services:
  - type: web
    name: skids-advanced
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_APP_URL
        value: https://skids-advanced.onrender.com
      - key: NEXT_PUBLIC_DEPLOYMENT_ENV
        value: production
      - key: NEXT_PUBLIC_TESTING_MODE
        value: false
      - key: NEXT_PUBLIC_MOCK_DATA
        value: true
