name: Deploy SKIDS Advanced to Production

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run type check
      run: npm run type-check
    
    - name: Build application
      run: npm run build
      env:
        NEXT_PUBLIC_APP_URL: https://skids-advanced.github.io
        NEXT_PUBLIC_DEPLOYMENT_ENV: production
        NEXT_PUBLIC_TESTING_MODE: false
        NEXT_PUBLIC_MOCK_DATA: true
        NODE_ENV: production
    
    - name: Test production build
      run: |
        npm start &
        sleep 10
        curl -f http://localhost:3000 || exit 1
        pkill -f "npm start"
    
    # Deploy to Railway (if configured)
    - name: Deploy to Railway
      if: github.ref == 'refs/heads/main'
      run: |
        echo "🚂 Ready for Railway deployment"
        echo "Connect your GitHub repo to Railway.app for automatic deployment"
    
    # Deploy to Render (if configured)
    - name: Deploy to Render
      if: github.ref == 'refs/heads/main'
      run: |
        echo "🎨 Ready for Render deployment"
        echo "Connect your GitHub repo to Render.com for automatic deployment"
    
    - name: Deployment Summary
      if: github.ref == 'refs/heads/main'
      run: |
        echo "🎉 Build completed successfully!"
        echo "📊 Deployment ready for:"
        echo "  - Railway.app"
        echo "  - Render.com"
        echo "  - Netlify"
        echo "  - Docker containers"
        echo "  - Manual server deployment"
